image: openjdk:11-jdk

variables:
  ANDROID_COMPILE_SDK: "34"                # Target SDK version
  ANDROID_BUILD_TOOLS: "34.0.0"            # Build tools version
  ANDROID_SDK_TOOLS: "8512546"             # Command-line tools version

before_script:
  - apt-get update -qq
  - apt-get install -qq -y wget tar unzip lib32stdc++6 lib32z1
  # Install Android SDK
  - wget -q https://dl.google.com/android/repository/commandlinetools-linux-${ANDROID_SDK_TOOLS}_latest.zip -O android-sdk.zip
  - unzip -q android-sdk.zip -d android-sdk
  - export ANDROID_SDK_ROOT="$PWD/android-sdk"
  - export PATH="$PATH:$ANDROID_SDK_ROOT/cmdline-tools/bin"
  # Accept licenses and install components
  - yes | sdkmanager --licenses
  - sdkmanager "platforms;android-${ANDROID_COMPILE_SDK}"
  - sdkmanager "build-tools;${ANDROID_BUILD_TOOLS}"
  - sdkmanager "platform-tools"

stages:
  - build

build_release:
  stage: build
  script:
    # Decode keystore and place it in the app directory
    - echo $KEYSTORE_BASE64 | base64 -d > app/keystore.jks
    # Build signed APK
    - ./gradlew assembleRelease
  artifacts:
    paths:
      - app/build/outputs/apk/release/*.apk   # Save APK as artifact
    expire_in: 1 week
  cache:
    paths:
      - .gradle/caches
      - .gradle/wrapper